name: publish npm pkg
'on':
  release:
    types:
      - created
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: yarn
      - run: yarn build
      - run: npm publish
        env:
          NPM_TOKEN: '${{secrets.NPM_TOKEN}}'
